### ISSUE TITLE
about the pretrain model

### ISSUE THREAD

**Issue by kou35** [xuyu0010/awesome-video-domain-adaptation#1]
I want to know where to get the pretrain model  "pretrained/tsn2d_rgb_r50.pth".
And the code in the file train_source_model.py, there is two parameter “end_epoch” in the function train_source_model.

**Comment by xuyu0010** [comment]
> I want to know where to get the pretrain model "pretrained/tsn2d_rgb_r50.pth". And the code in the file train_source_model.py, there is two parameter “end_epoch” in the function train_source_model.

Hi, maybe you have opened the issue in the wrong repository. Please report the issue in the relevant coding repository. This repository is only for summarization. Thank you!
