### ISSUE TITLE
New Paper on Source-free Video Domain Adaptation

### ISSUE THREAD

**Issue by avijit9** [xuyu0010/awesome-video-domain-adaptation#3]
Hi,

Would you be interested in adding this paper to the list too?

https://hal.archives-ouvertes.fr/hal-03929619/document

This is published at [ICVGIP](https://events.iitgn.ac.in/2022/icvgip/best_paper_awards.html) 2022

**Comment by xuyu0010** [comment]
Hi,

Sorry for the late reply and thank you for your suggestion. The paper is now added to the list.

Thank you for your interest and contribution!
