### ISSUE TITLE
Add paper: "Synthetic-to-Real Domain Adaptation for Action Recognition: A Dataset and Baseline Performances"

### ISSUE THREAD

**Issue by reddyav1** [xuyu0010/awesome-video-domain-adaptation#4]
I would like to suggest adding the following paper to the Closed-Set VDA section.

Title: Synthetic-to-Real Domain Adaptation for Action Recognition: A Dataset and Baseline Performances
IEEE Xplore: https://ieeexplore.ieee.org/document/10160416
Arxiv: https://arxiv.org/abs/2303.10280

Thanks for maintaining this list!

**Comment by xuyu0010** [comment]
Hi Arun,

Thank you very much for your interest in our repository and your contribution! The suggested paper has been added to the repository in our latest update!

Yuecong
